language: python
arch:
  - amd64
  - ppc64le
python:
  - 2.7
  - pypy
  - 3.4
  - 3.5
  - 3.6
  - 3.7
jobs:
      exclude:
       - arch : ppc64le
         python :  
            - "pypy"

script: python setup.py test
